### ISSUE TITLE
experiencing runtime errors while running simulations for scenario 7

### ISSUE THREAD

**Issue by kurtk92** [lvanhee/COVID-sim#126]
while running simulations, some runs are breaking due to the error below. It seems to originate from the needs model ... can someone help fix this?

**Run #22, RUNTIME ERROR: math operation produced a number too large for NetLogo
error while person 414 running /
  called by procedure SUE-FINANCIAL-SAFETY (/Applications/Netlogo-6.1.1/need_management.nls)
  called by procedure SDE-FINANCIAL-SAFETY (/Applications/Netlogo-6.1.1/need_management.nls)
  called by procedure GLOBAL-PREVALENCE-OF (/Applications/Netlogo-6.1.1/need_management.nls)
  called by procedure MY-PREFERRED-AVAILABLE-ACTIVITY-DESCRIPTOR (/Applications/Netlogo-6.1.1/people_decision.nls)
  called by procedure SELECT-ACTIVITY (/Applications/Netlogo-6.1.1/people_decision.nls)
  called by procedure PERFORM-PEOPLE-ACTIVITIES (/Applications/Netlogo-6.1.1/activity_model.nls)
  called by procedure GO
  called by procedure __EVALUATOR**
org.nlogo.nvm.RuntimePrimitiveException: math operation produced a number too large for NetLogo
	at org.nlogo.nvm.Instruction.invalidDouble(Instruction.scala:357)
	at org.nlogo.nvm.Instruction.validDouble(Instruction.scala:343)
	at org.nlogo.prim._asm_proceduresuefinancialsafetyapplicationsnetlogo611need_managementnls_report_13.perform(:3)
	at org.nlogo.nvm.Context.callReporterProcedure(Context.java:254)
	at org.nlogo.prim._asm_proceduresdefinancialsafetyapplicationsnetlogo611need_managementnls_setprocedurevariable_0.perform(:2)
	at org.nlogo.nvm.Context.callReporterProcedure(Context.java:254)
	at org.nlogo.prim._asm_procedureglobalprevalenceofapplicationsnetlogo611need_managementnls_setprocedurevariable_1.perform(:33)
	at org.nlogo.nvm.Context.callReporterProcedure(Context.java:254)
	at org.nlogo.prim._asm_proceduremypreferredavailableactivitydescriptorapplicationsnetlogo611people_decisionnl$d79c8a71282e7792e490e6898bf0540e$_list_10.report(:3)
	at org.nlogo.nvm.AnonymousReporter.report(AnonymousProcedure.scala:119)
	at org.nlogo.nvm.AnonymousReporter.report(AnonymousProcedure.scala:103)
	at org.nlogo.prim.etc._map.report(_map.scala:42)
	at org.nlogo.prim.etc._map.report(_map.scala:8)
	at org.nlogo.nvm.Instruction.argEvalList(Instruction.scala:151)
	at org.nlogo.prim.etc._reduce.report(_reduce.scala:14)
	at org.nlogo.prim._asm_proceduremypreferredavailableactivitydescriptorapplicationsnetlogo611people_decisionnl$d79c8a71282e7792e490e6898bf0540e$_report_6.perform(:2)
	at org.nlogo.nvm.Context.callReporterProcedure(Context.java:254)
	at org.nlogo.prim._asm_procedureselectactivityapplicationsnetlogo611people_decisionnls_setprocedurevariable_0.perform(:2)
	at org.nlogo.nvm.Context.runExclusive(Context.java:133)
	at org.nlogo.nvm.ExclusiveJob.run(ExclusiveJob.scala:39)
	at org.nlogo.nvm.Context.runExclusiveJob(Context.java:177)
	at org.nlogo.prim._asm_procedureperformpeopleactivitiesapplicationsnetlogo611activity_modelnls_ask_33.perform(:1)
	at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
	at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
	at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
	at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
	at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
	at org.nlogo.job.JobThread.run(JobThread.scala:66)

**Comment by rmellema** [comment]
Can you try to recreate this and send me an export? You can do that by pressing the export button in the interface and sending me the resulting .csv file.

**Comment by kurtk92** [comment]
the bug is fixed! it had to do with rounding an output to decimals
