### ISSUE TITLE
Crash: [unimplemented essential-shop essential shopping]

### ISSUE THREAD

**Issue by MelchiorUU** [lvanhee/COVID-sim#18]
Params default form github, infection on, animation off.

Log:

[unimplemented essential-shop essential shopping]
error while person 198 running ERROR
  called by procedure CAN-BE-DONE-WITH-A-DEPENDABLE-PERSON? (C:\phd\Corona\COVID-sim\activity_model.nls)
  called by procedure MY-AVAILABLE-ACTIVITY-DESCRIPTORS (C:\phd\Corona\COVID-sim\people_decision.nls)
  called by procedure MY-PREFERRED-AVAILABLE-ACTIVITY-DESCRIPTOR (C:\phd\Corona\COVID-sim\people_decision.nls)
  called by procedure SELECT-ACTIVITY (C:\phd\Corona\COVID-sim\people_decision.nls)
  called by procedure PERFORM-ACTIVITY (C:\phd\Corona\COVID-sim\activity_model.nls)
  called by procedure PERFORM-PEOPLE-ACTIVITIES (C:\phd\Corona\COVID-sim\activity_model.nls)
  called by procedure GO
  called by Button 'go'

org.nlogo.nvm.RuntimePrimitiveException: [unimplemented essential-shop essential shopping]
 at org.nlogo.prim.etc._error.perform(_error.scala:12)
 at org.nlogo.nvm.Context.callReporterProcedure(Context.java:254)
 at org.nlogo.prim._asm_proceduremyavailableactivitydescriptorscphdcoronacovidsimpeople_decisionnls_callreport_58.report(:1)
 at org.nlogo.nvm.AnonymousReporter.report(AnonymousProcedure.scala:119)
 at org.nlogo.nvm.AnonymousReporter.report(AnonymousProcedure.scala:103)
 at org.nlogo.prim.etc._filter.$anonfun$report$1(_filter.scala:19)
 at org.nlogo.prim.etc._filter.$anonfun$report$1$adapted(_filter.scala:18)
 at scala.collection.Iterator.foreach(Iterator.scala:941)
 at scala.collection.Iterator.foreach$(Iterator.scala:941)
 at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
 at scala.collection.IterableLike.foreach(IterableLike.scala:74)
 at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
 at org.nlogo.core.LogoList.foreach(LogoList.scala:24)
 at org.nlogo.prim.etc._filter.report(_filter.scala:18)
 at org.nlogo.prim.etc._filter.report(_filter.scala:11)
 at org.nlogo.prim._asm_proceduremyavailableactivitydescriptorscphdcoronacovidsimpeople_decisionnls_setprocedurevariable_57.perform()
 at org.nlogo.nvm.Context.callReporterProcedure(Context.java:254)
 at org.nlogo.prim._asm_proceduremypreferredavailableactivitydescriptorcphdcoronacovidsimpeople_decisionnls_callreport_9.report(:1)
 at org.nlogo.nvm.Instruction.argEvalList(Instruction.scala:151)
 at org.nlogo.prim.etc._reduce.report(_reduce.scala:14)
 at org.nlogo.prim._asm_proceduremypreferredavailableactivitydescriptorcphdcoronacovidsimpeople_decisionnls_report_5.perform()
 at org.nlogo.nvm.Context.callReporterProcedure(Context.java:254)
 at org.nlogo.prim._asm_procedureselectactivitycphdcoronacovidsimpeople_decisionnls_setprocedurevariable_0.perform(:2)
 at org.nlogo.nvm.Context.runExclusive(Context.java:133)
 at org.nlogo.nvm.ExclusiveJob.run(ExclusiveJob.scala:39)
 at org.nlogo.nvm.Context.runExclusiveJob(Context.java:177)
 at org.nlogo.prim._asm_procedureperformpeopleactivitiescphdcoronacovidsimactivity_modelnls_ask_11.perform(:1)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
 at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
 at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
 at scala.util.control.Exception$Catch.apply(Exception.scala:228)
 at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:66)

NetLogo 6.1.1
main: org.nlogo.app.AppFrame
thread: JobThread
Java HotSpot(TM) 64-Bit Server VM 1.8.0_202 (Oracle Corporation; 1.8.0_202-b08)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.8
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: covid-sim

04:36:01.867 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
04:36:01.720 DirtyEvent (org.nlogo.app.codetab.TemporaryCodeTab) AWT-EventQueue-0
04:36:01.687 DirtyEvent (org.nlogo.app.codetab.TemporaryCodeTab) AWT-EventQueue-0
04:36:01.604 RuntimeErrorEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:36:01.603 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
04:36:01.602 JobStoppingEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
04:36:01.540 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
04:36:01.540 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
04:36:01.540 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
04:36:01.540 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0

**Comment by MelchiorUU** [comment]
Also happens when infections is turned off.

**Comment by lvanhee** [comment]
Some parts of the procedure were missing. It should be fixed by now. 
Thank you for reporting.
