### ISSUE TITLE
Crash: [not implmplemented hospital mandatory]

### ISSUE THREAD

**Issue by MelchiorUU** [lvanhee/COVID-sim#19]
Default params from Github, infection on, animation off.

[not implmplemented hospital mandatory]
error while person 287 running ERROR
  called by procedure UPDATE-RESOURCE-BASED-ON-CURRENT-ACTIVITY (C:\phd\Corona\COVID-sim\activity_model.nls)
  called by procedure EXECUTE-ACTIVITY-EFFECT (C:\phd\Corona\COVID-sim\activity_model.nls)
  called by procedure PERFORM-PEOPLE-ACTIVITIES (C:\phd\Corona\COVID-sim\activity_model.nls)
  called by procedure GO
  called by Button 'go'

org.nlogo.nvm.RuntimePrimitiveException: [not implmplemented hospital mandatory]
 at org.nlogo.prim.etc._error.perform(_error.scala:12)
 at org.nlogo.nvm.Context.runExclusive(Context.java:133)
 at org.nlogo.nvm.ExclusiveJob.run(ExclusiveJob.scala:39)
 at org.nlogo.nvm.Context.runExclusiveJob(Context.java:177)
 at org.nlogo.prim._asm_procedureperformpeopleactivitiescphdcoronacovidsimactivity_modelnls_ask_14.perform(:1)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
 at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
 at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
 at scala.util.control.Exception$Catch.apply(Exception.scala:228)
 at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:66)

NetLogo 6.1.1
main: org.nlogo.app.AppFrame
thread: JobThread
Java HotSpot(TM) 64-Bit Server VM 1.8.0_202 (Oracle Corporation; 1.8.0_202-b08)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.8
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: covid-sim

04:39:42.154 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
04:39:42.143 RuntimeErrorEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:39:42.131 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
04:39:42.109 JobStoppingEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
04:39:42.029 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
04:39:42.029 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
04:39:42.029 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
04:39:42.029 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
04:39:42.029 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
04:39:42.029 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0

**Comment by lvanhee** [comment]
Some parts of the procedure were missing. It should be fixed by now. 
Thank you for reporting.
