### ISSUE TITLE
Runtime error: OF expected input to be an agent or agentset but got NOBODY instead.

### ISSUE THREAD

**Issue by MelchiorUU** [lvanhee/COVID-sim#46]
Settings:

![image](https://user-images.githubusercontent.com/59364209/77912960-c3dcae00-7293-11ea-88ae-415cd46d7ee7.png)

Log:

OF expected input to be an agent or agentset but got NOBODY instead.

org.nlogo.nvm.ArgumentTypeException: OF expected input to be an agent or agentset but got NOBODY instead.
 at org.nlogo.prim._of.report(_of.java:44)
 at org.nlogo.prim._asm_proceduremyavailableactivitydescriptorsdphdassocccovidsimpeople_decisionnls_list_28.report(:1)
 at org.nlogo.prim.etc._lput.report(_lput.java:14)
 at org.nlogo.prim._asm_proceduremyavailableactivitydescriptorsdphdassocccovidsimpeople_decisionnls_setprocedurevariable_27.perform()
 at org.nlogo.nvm.Context.callReporterProcedure(Context.java:254)
 at org.nlogo.prim._asm_proceduremypreferredavailableactivitydescriptordphdassocccovidsimpeople_decisionnls_callreport_9.report(:1)
 at org.nlogo.nvm.Instruction.argEvalList(Instruction.scala:151)
 at org.nlogo.prim.etc._reduce.report(_reduce.scala:14)
 at org.nlogo.prim._asm_proceduremypreferredavailableactivitydescriptordphdassocccovidsimpeople_decisionnls_report_5.perform()
 at org.nlogo.nvm.Context.callReporterProcedure(Context.java:254)
 at org.nlogo.prim._asm_procedureselectactivitydphdassocccovidsimpeople_decisionnls_setprocedurevariable_0.perform(:2)
 at org.nlogo.nvm.Context.runExclusive(Context.java:133)
 at org.nlogo.nvm.ExclusiveJob.run(ExclusiveJob.scala:39)
 at org.nlogo.nvm.Context.runExclusiveJob(Context.java:177)
 at org.nlogo.prim._asm_procedureperformpeopleactivitiesdphdassocccovidsimactivity_modelnls_ask_13.perform(:1)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
 at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
 at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
 at scala.util.control.Exception$Catch.apply(Exception.scala:228)
 at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:66)

NetLogo 6.1.1
main: org.nlogo.app.AppFrame
thread: JobThread
Java HotSpot(TM) 64-Bit Server VM 1.8.0_202 (Oracle Corporation; 1.8.0_202-b08)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.8
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: covid-sim

02:31:09.607 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
02:31:09.604 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
02:31:09.560 DirtyEvent (org.nlogo.app.codetab.TemporaryCodeTab) AWT-EventQueue-0
02:31:09.546 DirtyEvent (org.nlogo.app.codetab.TemporaryCodeTab) AWT-EventQueue-0
02:31:09.505 RuntimeErrorEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:31:09.453 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
02:31:09.452 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
02:31:09.452 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
02:31:09.452 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
02:31:09.452 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0

**Comment by MelchiorUU** [comment]
Seems to occur when there are less than 5 essential shops.

**Comment by rmellema** [comment]
What file/line/graph is this from? You included the Java stacktrace, but that does not tell us much about where the error is.

**Comment by MelchiorUU** [comment]
Where can I see that?

**Comment by rmellema** [comment]
Netlogo should indicate that when it throws the error, and bring the line/thing into focus

**Comment by MelchiorUU** [comment]
people_decisions.nls, line 59:

      set activities lput (list [other-end] of one-of my-gathering-links with [member? "essential shopping" features] "essential shopping") activities

**Comment by rmellema** [comment]
Found it! The problem was a priority problem with `ceiling` and multiplication, making sure that the agents might end up with zero essential shops. Pull request #47 fixes this issue
(If you go to files you can also quickly see what change you need to make to fix it)
